
package org.cuahsi.his._1_0.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WaterOneFlow", targetNamespace = "http://www.cuahsi.org/his/1.0/ws/", wsdlLocation = "http://river.sdsc.edu/waterOneFlow/NWIS/DailyValues.asmx?WSDL")
public class WaterOneFlow
    extends Service
{

    //private final static URL WATERONEFLOW_WSDL_LOCATION;
    //private final static Logger logger = Logger.getLogger(org.cuahsi.his._1_0.ws.WaterOneFlow.class.getName());

    public WaterOneFlow ( String wsdlLocation )
    throws MalformedURLException
    {
        super(
            new URL(org.cuahsi.his._1_0.ws.WaterOneFlow.class.getResource("."),wsdlLocation),
            new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlow"));
    /* SAM 2012-03-08 The following is what the wsimport JDK program generated.
    Modify so that the WSDL can be specified in the constructor in a more generic way
    static {
        /*
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.cuahsi.his._1_0.ws.WaterOneFlow.class.getResource(".");
            url = new URL(baseUrl, "http://river.sdsc.edu/waterOneFlow/NWIS/DailyValues.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://river.sdsc.edu/waterOneFlow/NWIS/DailyValues.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WATERONEFLOW_WSDL_LOCATION = url;
        */
    }

    public WaterOneFlow(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    //public WaterOneFlow() {
    //    super(WATERONEFLOW_WSDL_LOCATION, new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlow"));
    //}

    /**
     * 
     * @return
     *     returns WaterOneFlowSoap
     */
    @WebEndpoint(name = "WaterOneFlowSoap")
    public WaterOneFlowSoap getWaterOneFlowSoap() {
        return super.getPort(new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlowSoap"), WaterOneFlowSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WaterOneFlowSoap
     */
    @WebEndpoint(name = "WaterOneFlowSoap")
    public WaterOneFlowSoap getWaterOneFlowSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlowSoap"), WaterOneFlowSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WaterOneFlowSoap
     */
    @WebEndpoint(name = "WaterOneFlowSoap12")
    public WaterOneFlowSoap getWaterOneFlowSoap12() {
        return super.getPort(new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlowSoap12"), WaterOneFlowSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WaterOneFlowSoap
     */
    @WebEndpoint(name = "WaterOneFlowSoap12")
    public WaterOneFlowSoap getWaterOneFlowSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cuahsi.org/his/1.0/ws/", "WaterOneFlowSoap12"), WaterOneFlowSoap.class, features);
    }

}
